# # version: '3.8'

# services:

#   db:
#     image: postgres:15
#     container_name: attendance_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: attendance
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 10

#   backend:
#     build: ./backend
#     container_name: attendance_backend
#     restart: always
#     depends_on:
#       db:
#         condition: service_healthy
#     ports:
#       - "4040:4040"
#     environment:
#       JWT_SECRET: 54657d5cdc6b81baf001f492ce508a16c9ac8dd33e5829692006b8a73b98844f3d389e92fdce5220ecf4606f9e0b7e6771382e5afc72b2dc2c0a4ed41f4b4f26
#       DATABASE_URL: postgresql://postgres:postgres@db:5432/attendance

# volumes:
#   db_data:
services:

  mongo:
    image: mongo:7
    container_name: attendance-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-secret}
      MONGO_INITDB_DATABASE: attendance
    volumes:
      - mongo-data:/data/db
    # ports:
    #   - "27017:27017"          # remove this line if you don't need external access
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attendance-backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: 4040
      MONGO_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-secret}@mongo:27017/attendance?authSource=admin
      JWT_SECRET: 54657d5cdc6b81baf001f492ce508a16c9ac8dd33e5829692006b8a73b98844f3d389e92fdce5220ecf4606f9e0b7e6771382e5afc72b2dc2c0a4ed41f4b4f26
      QR_SECRET: 54657d5cdc6b81baf001f492ce508a16c9ac8dd33e5829692006b8a73b98844f3d389e92fdce5220ecf4606f9e0b7e6771382e5afc72b2dc2c0a4ed41f4b4f26
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      AT_RISK_THRESHOLD: ${AT_RISK_THRESHOLD:-75}
      BACKUP_DIR: /app/backups
    volumes:
      - backups:/app/backups
    ports:
      - "4040:4040"

volumes:
  mongo-data:
  backups: