const express  = require('express');
const { v4: uuidv4 } = require('uuid');
const Session  = require('../models/Session');
const Course   = require('../models/Course');
const { authenticate } = require('../middleware/auth');

const router = express.Router();

// ── Helper ────────────────────────────────────────────────────────────────────
async function findActiveSessions(courseId) {
  return Session.find({
    course: courseId,
    $expr: {
      $gt: [
        { $add: ['$timestamp', { $multiply: ['$duration', 60000] }] },
        new Date(),
      ],
    },
  }).lean();
}

// ── POST /startSession ────────────────────────────────────────────────────────
// A lecture can have multiple simultaneous sessions (BLE, QR, Manual each separately).
// Guard: one active session per (course, lectureUID, method).
router.post('/startSession', authenticate, async (req, res, next) => {
  try {
    const { course_id, mode, lectureUID } = req.body;
    if (!course_id || !mode) {
      return res.status(400).json({ error: 'course_id and mode are required' });
    }

    const course = await Course.findById(course_id).lean();
    if (!course) return res.status(404).json({ error: 'Course not found' });

    const uid     = req.user.user_id;
    const allowed = req.user.role === 'admin'
      || course.instructors.includes(uid)
      || (course.tas || []).includes(uid);
    if (!allowed) return res.status(403).json({ error: 'Forbidden' });

    // Resolve lectureUID
    let resolvedLectureUID = lectureUID;
    let scheduledTime      = new Date();
    const duration         = 50;

    if (!resolvedLectureUID) {
      const now      = new Date();
      const upcoming = course.lectures
        .filter(l => !l.cancelled && new Date(l.scheduledTime) <= now)
        .sort((a, b) => new Date(b.scheduledTime) - new Date(a.scheduledTime))[0];
      resolvedLectureUID = upcoming?.lectureUID || uuidv4();
      if (upcoming) scheduledTime = upcoming.scheduledTime;
    } else {
      const lec = course.lectures.find(l => l.lectureUID === resolvedLectureUID);
      if (lec) scheduledTime = lec.scheduledTime;
    }

    // Guard: no duplicate active session for same method on this lecture
    const existingForMethod = await Session.findOne({
      course:     course_id,
      lectureUID: resolvedLectureUID,
      method:     mode,
      $expr: {
        $gt: [
          { $add: ['$timestamp', { $multiply: ['$duration', 60000] }] },
          new Date(),
        ],
      },
    }).lean();

    if (existingForMethod) {
      return res.status(409).json({
        error:      `An active ${mode} session already exists for this lecture`,
        session_id: existingForMethod.sessionUID,
      });
    }

    const session = await Session.create({
      course:          course_id,
      lectureUID:      resolvedLectureUID,
      scheduledTime,
      duration,
      method:          mode,
      isAutoGenerated: false,
    });

    res.status(201).json({
      session_id: session.sessionUID,
      lectureUID: resolvedLectureUID,
      method:     mode,
    });
  } catch (err) { next(err); }
});

// ── POST /endSession/:sessionId ───────────────────────────────────────────────
router.post('/endSession/:sessionId', authenticate, async (req, res, next) => {
  try {
    const session = await Session.findOne({ sessionUID: req.params.sessionId });
    if (!session) return res.status(404).json({ error: 'Session not found' });
    const elapsed = Math.ceil((Date.now() - session.timestamp.getTime()) / 60000) || 1;
    session.duration = elapsed;
    await session.save();
    res.json({ message: 'Session ended', session_id: session.sessionUID });
  } catch (err) { next(err); }
});

// ── GET /activeSession?course_id=... ─────────────────────────────────────────
// Returns ALL active sessions for a course.
// Primary field for backward-compat + activeSessions[] for multi-session UI.
router.get('/activeSession', authenticate, async (req, res, next) => {
  try {
    const { course_id } = req.query;
    if (!course_id) return res.status(400).json({ error: 'course_id required' });

    const sessions = await findActiveSessions(course_id);
    if (sessions.length === 0) return res.json({});

    const primary = sessions.sort((a, b) => b.timestamp - a.timestamp)[0];
    res.json({
      session_id:     primary.sessionUID,
      method:         primary.method,
      lectureUID:     primary.lectureUID,
      startedAt:      primary.timestamp,
      activeSessions: sessions.map(s => ({
        session_id: s.sessionUID,
        method:     s.method,
        lectureUID: s.lectureUID,
        startedAt:  s.timestamp,
      })),
    });
  } catch (err) { next(err); }
});

// ── GET /admin/sessions ───────────────────────────────────────────────────────
router.get('/admin/sessions', authenticate, async (req, res, next) => {
  try {
    if (req.user.role !== 'admin') return res.status(403).json({ error: 'Forbidden' });
    const sessions = await Session.find().sort({ timestamp: -1 }).limit(200).lean();
    res.json(sessions.map(s => ({ ...s, session_id: s.sessionUID, course_id: s.course })));
  } catch (err) { next(err); }
});

module.exports = router;