const { v4: uuidv4 } = require("uuid");
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");

const Student = require("../models/Student");
const Professor = require("../models/Professor");
const Admin = require("../models/Admin");
const Course = require("../models/Course");
const Session = require("../models/Session");
const Attendance = require("../models/Attendance");
const Enrollment = require("../models/Enrollment");
const Classroom = require("../models/Classroom");
const Beacon = require("../models/Beacon");

const MONGO_URI = process.env.MONGO_URI;

const NUM_STUDENTS = 120;
const START_DATE = new Date("2026-01-01");

const rand = (p) => Math.random() < p;

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected");

  await Promise.all([
    Student.deleteMany({}),
    Professor.deleteMany({}),
    Admin.deleteMany({}),
    Course.deleteMany({}),
    Session.deleteMany({}),
    Attendance.deleteMany({}),
    Enrollment.deleteMany({}),
    Classroom.deleteMany({}),
    Beacon.deleteMany({})
  ]);

  // ---------------- ADMIN ----------------
  await Admin.create({
    _id: "admin",
    password: await bcrypt.hash("adminpass", 10),
    email: "admin@test.com"
  });

  // ---------------- PROFESSORS ----------------
  const profs = [];
  for (let i = 1; i <= 3; i++) {
    profs.push(await Professor.create({
      _id: `prof_${i}`,
      name: `Prof ${i}`,
      email: `prof${i}@test.com`,
      password: await bcrypt.hash("pass", 10),
    }));
  }

  // ---------------- STUDENTS ----------------
  const students = [];
  for (let i = 1; i <= NUM_STUDENTS; i++) {
    students.push(await Student.create({
      _id: `stud_${i}`,
      name: `Student ${i}`,
      email: `stud${i}@test.com`,
      password: await bcrypt.hash("pass", 10),
      imageURL: `https://api.dicebear.com/7.x/initials/svg?seed=Student${i}`
    }));
  }

  // ---------------- TAs (subset of students) ----------------
  const tas = students.slice(0, 9).map(s => s._id);

  // ---------------- CLASSROOMS ----------------
  const classrooms = [];
  for (let i = 1; i <= 3; i++) {
    classrooms.push(await Classroom.create({
      _id: `room_${i}`,
      capacity: 120
    }));
  }

  // ---------------- BEACONS ----------------
  for (let i = 0; i < classrooms.length; i++) {
    for (let j = 0; j < 3; j++) {
      await Beacon.create({
        bleID: `BLE_${i+1}_${j+1}`,
        classroom: classrooms[i]._id
      });
    }
  }

  // ---------------- COURSES ----------------
  const courses = [];

  for (let i = 0; i < 3; i++) {
    const lectures = [];

    let current = new Date(START_DATE);

    // create ~10 lectures
    for (let l = 0; l < 10; l++) {
      lectures.push({
        lectureUID: uuidv4(),
        scheduledTime: new Date(current)
      });
      current.setDate(current.getDate() + 7);
    }

    const course = await Course.create({
      _id: `course_${i+1}`,
      name: ["DSA", "DBMS", "OS"][i],
      department: "CSE",
      slot: ["A", "B", "C"][i],
      venue: classrooms[i]._id,
      startDate: START_DATE,
      endDate: new Date(),
      instructors: [profs[i]._id],
      tas: tas.slice(i*3, i*3+3),
      lectures
    });

    courses.push(course);
  }

  // ---------------- ENROLLMENTS ----------------
  for (const student of students) {
    for (const course of courses) {
      if (rand(0.8) && !tas.includes(student._id)) {
        await Enrollment.create({
          student: student._id,
          course: course._id
        });
      }
    }
  }

  // ---------------- SESSIONS ----------------
  const allSessions = [];

  for (const course of courses) {
    for (const lecture of course.lectures) {

      // 1–2 sessions per lecture
      const sessionCount = rand(0.5) ? 1 : 2;

      for (let i = 0; i < sessionCount; i++) {
        const session = await Session.create({
          sessionUID: uuidv4(),
          course: course._id,
          lectureUID: lecture.lectureUID,
          scheduledTime: lecture.scheduledTime,
          duration: 60,
          method: ["BLE", "QRCode", "Manual"][Math.floor(Math.random()*3)],
          isAutoGenerated: rand(0.2)
        });

        allSessions.push(session);
      }
    }
  }

  // ---------------- ATTENDANCE ----------------
  for (const session of allSessions) {
    const enrolled = await Enrollment.find({ course: session.course });

    for (const e of enrolled) {
      if (rand(0.75)) {
        await Attendance.create({
          sessionUID: session.sessionUID,
          student: e.student,
          verifiedVia: session.method,
          markedAt: new Date(session.scheduledTime)
        });
      }
    }
  }

  console.log("✅ Seeding complete");
  process.exit();
}

seed();