const Course   = require('../models/Course');
const Session  = require('../models/Session');

const DAY_NAMES = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

/**
 * For every lecture starting right now (±2 min window):
 *  - If the lecture has a covering schedule with switch=true → skip (scheduler handles it)
 *  - If NO schedule covers it → create one 5-min BLE fallback session
 *    (only if no session of ANY method already exists for this lecture)
 */
async function autoCreateFallbackSessions() {
  const now       = new Date();
  const todayName = DAY_NAMES[now.getDay()];
  const windowStart = new Date(now.getTime() - 2 * 60000);
  const windowEnd   = new Date(now.getTime() + 2 * 60000);

  const courses = await Course.find({
    'lectures.scheduledTime': { $gte: windowStart, $lte: windowEnd },
    'lectures.cancelled':     false,
  }).lean();

  for (const course of courses) {
    const dueLectures = course.lectures.filter(l =>
      !l.cancelled &&
      new Date(l.scheduledTime) >= windowStart &&
      new Date(l.scheduledTime) <= windowEnd
    );

    for (const lecture of dueLectures) {
      const lecMin = (() => {
        const t = new Date(lecture.scheduledTime);
        return t.getHours() * 60 + t.getMinutes();
      })();

      // Does a schedule cover this lecture's time slot today?
      const covered = (course.schedules || []).some(s => {
        if (s.scheduledDay !== todayName) return false;
        const [sh, sm] = s.startTime.split(':').map(Number);
        const [eh, em] = s.endTime.split(':').map(Number);
        return lecMin >= sh * 60 + sm && lecMin < eh * 60 + em;
      });

      if (covered) continue;

      // Any session already exists for this lecture (any method)?
      const existing = await Session.findOne({
        course:     course._id,
        lectureUID: lecture.lectureUID,
      }).lean();

      if (existing) continue;

      await Session.create({
        course:          course._id,
        lectureUID:      lecture.lectureUID,
        scheduledTime:   lecture.scheduledTime,
        duration:        5,
        method:          'BLE',
        isAutoGenerated: true,
      });

      console.log(`[AutoSession] 5-min BLE fallback for ${course._id} / ${lecture.lectureUID}`);
    }
  }
}

module.exports = { autoCreateFallbackSessions };