const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const SessionSchema = new mongoose.Schema({
  sessionUID: {
    type:    String,
    default: uuidv4,
    unique:  true,
  },
  course: {
    type:     String,
    required: true,
    ref:      'Course',
  },
  lectureUID: {
    type:     String,
    required: true,
    // NOT unique per course — a lecture can have many sessions.
    // A student is present for a lecture only if they attended ALL sessions.
  },
  scheduledTime: {
    type:     Date,
    required: true,
  },
  duration: {
    type:     Number, // minutes
    required: true,
  },
  method: {
    type:     String,
    enum:     ['BLE', 'QRCode', 'Manual'],
    required: true,
  },
  isAutoGenerated: {
    type:    Boolean,
    default: false,
  },
  timestamp: {
    type:    Date,
    default: Date.now,
  },
});

SessionSchema.index({ course: 1, lectureUID: 1 });       // all sessions for a lecture
SessionSchema.index({ course: 1, timestamp: -1 });        // active-session check

module.exports = mongoose.model('Session', SessionSchema);